export const GET_ORDER_DATA_REQUEST: "GET_ORDER_DATA_REQUEST" = "GET_ORDER_DATA_REQUEST";
export const GET_ORDER_DATA_SUCCESS: "GET_ORDER_DATA_SUCCESS" = "GET_ORDER_DATA_SUCCESS";
export const GET_ORDER_DATA_ERROR: "GET_ORDER_DATA_ERROR" = "GET_ORDER_DATA_ERROR";