export const USER_ORDERS_WS_CONNECTION_START: 'USER_ORDERS_WS_CONNECTION_START' = 'USER_ORDERS_WS_CONNECTION_START';
export const USER_ORDERS_WS_CONNECTION_CLOSE: 'USER_ORDERS_WS_CONNECTION_CLOSE' = 'USER_ORDERS_WS_CONNECTION_CLOSE';
export const USER_ORDERS_WS_CONNECTION_SUCCESS: 'USER_ORDERS_WS_CONNECTION_SUCCESS' = 'USER_ORDERS_WS_CONNECTION_SUCCESS';
export const USER_ORDERS_WS_CONNECTION_ERROR: 'USER_ORDERS_WS_CONNECTION_ERROR' = 'USER_ORDERS_WS_CONNECTION_ERROR';
export const USER_ORDERS_WS_CONNECTION_CLOSED: 'USER_ORDERS_WS_CONNECTION_CLOSED' = 'USER_ORDERS_WS_CONNECTION_CLOSED';
export const USER_ORDERS_WS_CONNECTION_GET_MESSAGE: 'USER_ORDERS_WS_CONNECTION_GET_MESSAGE' = 'USER_ORDERS_WS_CONNECTION_GET_MESSAGE';
export const USER_ORDERS_WS_CONNECTION_SEND_MESSAGE: 'USER_ORDERS_WS_CONNECTION_SEND_MESSAGE' = 'USER_ORDERS_WS_CONNECTION_SEND_MESSAGE';