export const GET_USER_DATA_REQUEST: "GET_USER_DATA_REQUEST" = "GET_USER_DATA_REQUEST";
export const GET_USER_DATA_SUCCESS: "GET_USER_DATA_SUCCESS" = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_ERROR: "GET_USER_DATA_ERROR" = "GET_USER_DATA_ERROR";
export const EDIT_USER_DATA_REQUEST: "EDIT_USER_DATA_REQUEST" = "EDIT_USER_DATA_REQUEST";
export const EDIT_USER_DATA_SUCCESS: "EDIT_USER_DATA_SUCCESS" = "EDIT_USER_DATA_SUCCESS";
export const EDIT_USER_DATA_ERROR: "EDIT_USER_DATA_ERROR" = "EDIT_USER_DATA_ERROR";