import {
  FEED_WS_CONNECTION_CLOSED,
  FEED_WS_CONNECTION_ERROR, FEED_WS_CONNECTION_GET_MESSAGE,
  FEED_WS_CONNECTION_SEND_MESSAGE,
  FEED_WS_CONNECTION_START,
  FEED_WS_CONNECTION_SUCCESS
} from "../constants/feed";

export type TWsActions = {
  wsInit: typeof FEED_WS_CONNECTION_START,
  wsSendMessage?: typeof FEED_WS_CONNECTION_SEND_MESSAGE,
  onOpen: typeof FEED_WS_CONNECTION_SUCCESS,
  onClose: typeof FEED_WS_CONNECTION_CLOSED,
  onError: typeof FEED_WS_CONNECTION_ERROR,
  onMessage: typeof FEED_WS_CONNECTION_GET_MESSAGE
}